// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vaccinator.Controllers;

namespace Vaccinator.Migrations
{
    [DbContext(typeof(ContextBDD))]
    [Migration("20210407151704_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Vaccinator.Models.Injection", b =>
                {
                    b.Property<string>("uuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePrise")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateRappel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Maladie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumLot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Personneuuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("StatusRappel")
                        .HasColumnType("INTEGER");

                    b.HasKey("uuid");

                    b.HasIndex("Personneuuid");

                    b.ToTable("Injections");
                });

            modelBuilder.Entity("Vaccinator.Models.Personne", b =>
                {
                    b.Property<string>("uuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ddn")
                        .HasColumnType("TEXT");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<char>("sexe")
                        .HasColumnType("TEXT");

                    b.HasKey("uuid");

                    b.ToTable("Personnes");
                });

            modelBuilder.Entity("Vaccinator.Models.Injection", b =>
                {
                    b.HasOne("Vaccinator.Models.Personne", "Personne")
                        .WithMany("injections")
                        .HasForeignKey("Personneuuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("Vaccinator.Models.Personne", b =>
                {
                    b.Navigation("injections");
                });
#pragma warning restore 612, 618
        }
    }
}
